spring:
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                default_batch_fetch_size: 100
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${JDBC_URL}
        username: ${JDBC_USERNAME}
        password: ${JDBC_PASSWORD}

---
spring.config.activate.on-profile: local

spring:
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        url: ${testcontainers.mysql.url}
        username: ${testcontainers.mysql.username}
        password: ${testcontainers.mysql.password}

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prod

